version: '3'
services:
  vote:
    build: ./vote
    ports:
      - "8081:80"
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier
      
  result:
    build: ./result
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier
  
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier
  
  redis:
    image: "redis:latest"
    networks:
      - back-tier
  
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: